model_list:
  - model_name: "*"             # all requests where model not in your config go to this deployment
    litellm_params:
      model: "*"           # passes our validation check that a real provider is given
